spring.application.name=calculator
climatiq.api.key=9302NRQMN56Z9EGE06A0Q4FDH8
climatiq.api.url=https://api.climatiq.io/data/v1/estimate
spring.datasource.url=jdbc:mysql://localhost:3306/sintropia
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name:com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

jwt.secret=c}qawzs(@&&@r-xwsedrcftvgybnhjkvgbrwa123wx!!@%@T&!rf!!!!!f 

